mod matcher;
mod rule_fve;
mod rule_ive;
mod rule_t;

use crate::Atom;
use std::collections::HashMap;

pub use matcher::*;

pub type SolutionSet = HashMap<Atom, Atom>;

#[derive(Clone)]
pub struct MatchEquation {
    pattern: Atom,
    ground: Atom,
}

pub struct Substitution {
    variable: Atom,
    ground: Atom,
}

pub trait MatchRule: Sized + MatchGenerator {
    /// Checks if this rule applies to the active match equation, constructing a
    /// generator if it does.
    fn try_rule(match_equation: &MatchEquation) -> Option<Self>;
}

pub type MatchResultList = Vec<MatchResult>;

pub enum MatchResult {
    MatchEquation(MatchEquation),
    Substitution(Substitution),
}

/// A `MatchGenerator` iterates over every way it can transform a match equation and
/// every solution generated by that transformation.
pub trait MatchGenerator: Iterator<Item = MatchResultList> {
    /// Returns the match equation that this match generator was created to solve.
    fn match_equation(&self) -> MatchEquation;
}
