mod matcher;
mod rule_fve;
mod rule_ive;
mod rule_t;

use crate::Expr;
use std::collections::HashMap;

use crate::symbol::Symbol;
pub use matcher::*;

pub type SolutionSet = HashMap<Expr, Expr>;

#[derive(Clone, PartialEq, Debug)]
pub struct MatchEquation {
    pattern: Expr,
    ground: Expr,
}

#[derive(PartialEq, Debug)]
pub struct Substitution {
    variable: Symbol,
    pattern: Expr,
    ground: Expr,
}

pub trait MatchRule: Sized + MatchGenerator {
    /// Checks if this rule applies to the active match equation, constructing a generator if it
    /// does.
    fn try_rule(match_equation: &MatchEquation) -> Option<Self>;
}

pub type MatchResultList = Vec<MatchResult>;

#[derive(PartialEq, Debug)]
pub enum MatchResult {
    MatchEquation(MatchEquation),
    Substitution(Substitution),
}

/// A `MatchGenerator` iterates over every way it can transform a match equation and
/// every solution generated by that transformation.
pub trait MatchGenerator: Iterator<Item = MatchResultList> {
    /// Returns the match equation that this match generator was created to solve.
    fn match_equation(&self) -> MatchEquation;
}
